### PR TITLE
Fix feather icons

### LINKED ISSUE #945: styled-icons/feather/ArrowUpCircle and down arrow = blank
styled-icons/feather/ArrowUpCircle and styled-icons/feather/ArrowDownCircle is missing the arrow its just a blank circle

### PR DESCRIPTION
**Pull request by stramel**
Fixes #945 

Currently, we overwrite any `fill="none"` with `fill="currentColor". In the case of the feather icon pack, they specifically use `stroke="currentColor"`. This change maintains the `fill="none"` if using `stroke="currentColor"`. Feels a _bit_ on the fragile side but should address the issue.

Also, the regex that I provided to SVGO for `removeAttrs` was a bit aggressive in #938. So I modified it to also maintain the value `currentColor`. This _should_ allow for us to maintain properly set up icons.

Ran locally to verify:

image

Did a quick skim on each icon pack as well. I didn't immediately notice anything standing out/broken. @jacobwgillespie Would love to see if we could get some visual regression tests for all the icons automated so it would be easier to tell if changes are going to break an icon or icon pack.

### CODE REVIEW

**Comment by stramel** [comment]
Trying one more thing really quick.

File: packages/styled-icons/generate/generate.js [hunk 1]
```diff
@@ -126,11 +126,6 @@ const generate = async () => {
       }
     }
 
-    // If the base icon has a fill of `none`, replace it
-    if (icon.attrs.fill === 'none') {
```
Comment (stramel) [inline packages/styled-icons/generate/generate.js]: I can optionally, re-add this to where it does a check that `stroke !== 'currentColor'` again if you want @jacobwgillespie. However, it does work without it. The issue wasn't that `fill` was `none` but that I had stripped out the `stroke="currentColor"`

Comment (jacobwgillespie) [reply packages/styled-icons/generate/generate.js]: Cool, yeah this was my attempt to fix this issue that only half worked, I'm cool with removing the partial measure!

**Comment by jacobwgillespie** [comment]
> Would love to see if we could get some visual regression tests for all the icons automated so it would be easier to tell if changes are going to break an icon or icon pack.

Totally, this would be awesome!  There's probably a nice pre-built way to do this with Storybook or something.  If I get some spare time (which is rare these days!) I'll take a look, or feel free to check it out yourself!
